**TO DO TASK**

Exercise on Functions

Task1

In [1]:
def convert_units(conversion_type, value):
    """
    Converts units based on the selected conversion type.

    """

    if conversion_type == "1":  # meters to feet
        return value * 3.28084

    elif conversion_type == "2":  # feet to meters
        return value / 3.28084

    elif conversion_type == "3":  # kg to pounds
        return value * 2.20462

    elif conversion_type == "4":  # pounds to kg
        return value / 2.20462

    elif conversion_type == "5":  # liters to gallons
        return value * 0.264172

    elif conversion_type == "6":  # gallons to liters
        return value / 0.264172

    else:
        return None


def unit_converter():
    """Main function that interacts with the user and performs unit conversion."""

    print("Select the conversion you want to perform:\n")

    print("1. Convert Meters (m) → Feet (ft)")
    print("2. Convert Feet (ft) → Meters (m)")
    print("3. Convert Kilograms (kg) → Pounds (lbs)")
    print("4. Convert Pounds (lbs) → Kilograms (kg)")
    print("5. Convert Liters (L) → Gallons (gal)")
    print("6. Convert Gallons (gal) → Liters (L)\n")

    conversion_type = input("Enter the number corresponding to your choice (1–6): ")

    try:
        value = float(input("Enter the value you want to convert: "))

        result = convert_units(conversion_type, value)

        if result is None:
            print("Error: Invalid conversion option selected.")
        else:
            print("Converted value =", result)

    except ValueError:
        print("Error: Please enter a valid numeric value.")


unit_converter()

Select the conversion you want to perform:

1. Convert Meters (m) → Feet (ft)
2. Convert Feet (ft) → Meters (m)
3. Convert Kilograms (kg) → Pounds (lbs)
4. Convert Pounds (lbs) → Kilograms (kg)
5. Convert Liters (L) → Gallons (gal)
6. Convert Gallons (gal) → Liters (L)

Enter the number corresponding to your choice (1–6): 1
Enter the value you want to convert: 10
Converted value = 32.8084


Task 2

In [2]:
def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    """
    return sum(numbers)


def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.

    """
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Finds the maximum value in a list of numbers.

    """
    return max(numbers)


def find_min(numbers):
    """
    Finds the minimum value in a list of numbers.

    """
    return min(numbers)


def main():
    """Main function that asks the user for operation choice and numbers."""

    print("Choose the operation you want to perform:\n")

    print("1. Find the Sum of the numbers")
    print("2. Find the Average of the numbers")
    print("3. Find the Maximum number")
    print("4. Find the Minimum number\n")

    choice = input("Enter the number corresponding to your choice (1–4): ")

    try:
        numbers_input = input(
            "Enter a list of numbers separated by spaces (example: 10 20 30 40): "
        )

        numbers = [float(num) for num in numbers_input.split()]

        if len(numbers) == 0:
            print("Error: The list of numbers cannot be empty.")
            return

        if choice == "1":
            result = calculate_sum(numbers)
            print("The sum of the numbers is:", result)

        elif choice == "2":
            result = calculate_average(numbers)
            print("The average of the numbers is:", result)

        elif choice == "3":
            result = find_max(numbers)
            print("The maximum number is:", result)

        elif choice == "4":
            result = find_min(numbers)
            print("The minimum number is:", result)

        else:
            print("Error: Invalid operation selected.")

    except ValueError:
        print("Error: Please enter valid numeric values only.")


main()

Choose the operation you want to perform:

1. Find the Sum of the numbers
2. Find the Average of the numbers
3. Find the Maximum number
4. Find the Minimum number

Enter the number corresponding to your choice (1–4): 3
Enter a list of numbers separated by spaces (example: 10 20 30 40): 45 66 91 12
The maximum number is: 91.0


Exercise on List Manipulation:

In [3]:
#1. Extract Every Other Element:
def extract_every_other(lst):
    """Return every other element from the list, starting with the first element."""
    return lst[::2]

numbers = [3, 4, 5, 6, 7, 8]

result = extract_every_other(numbers)

print("Original list:", numbers)
print("Every other element:", result)

Original list: [3, 4, 5, 6, 7, 8]
Every other element: [3, 5, 7]


In [5]:
#2. Slice a Sublist:
def get_sublist(lst, start, end):
    """
    This function returns a part of the list from start index to end index.
    """
    return lst[start:end+1]

numbers = [3, 4, 5, 6, 7, 8]
print(get_sublist(numbers, 1, 4))

[4, 5, 6, 7]


In [6]:
#3. Reverse a List Using Slicing:
def reverse_list(lst):
    """
    This function reverses the list using slicing.
    """
    return lst[::-1]

numbers = [3, 4, 5, 6, 7, 8]
print(reverse_list(numbers))

[8, 7, 6, 5, 4, 3]


In [7]:
#4. Remove the First and Last Elements:
def remove_first_last(lst):
    """
    This function removes the first and last elements of a list.
    """
    return lst[1:-1]

numbers = [3, 4, 5, 6, 7, 8]
print(remove_first_last(numbers))

[4, 5, 6, 7]


In [8]:
#5. Get the First n Elements:
def get_first_n(lst, n):
    """
    This function returns the first n elements of a list.
    """
    return lst[:n]

numbers = [3, 4, 5, 6, 7, 8]
print(get_first_n(numbers, 2))

[3, 4]


In [9]:
#6. Extract Elements from the End:
def get_last_n(lst, n):
    """
    This function returns the last n elements of a list.
    """
    return lst[-n:]

numbers = [3, 4, 5, 6, 7, 8]
print(get_last_n(numbers, 3))

[6, 7, 8]


In [10]:
#7. Extract Elements in Reverse Order:
def reverse_skip(lst):
    """
    This function returns every second element from the list
    starting from the second last element going backwards.
    """
    return lst[-2::-2]

numbers = [3, 4, 5, 6, 7, 8]
print(reverse_skip(numbers))

[7, 5, 3]


Exercise on Nested List:

In [11]:
# 1. Flatten a Nested List
def flatten(lst):
    """Flatten a nested list into a single list."""
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(item)
        else:
            flat_list.append(item)
    return flat_list

nested_list1 = [[10, 20], [30, 40], [50]]
print("Flattened:", flatten(nested_list1))


Flattened: [10, 20, 30, 40, 50]


In [12]:
# 2. Accessing Nested List Elements
def access_nested_element(lst, indices):
    """
    Extracts an element from a nested list using given indices.

    """

    element = lst
    for index in indices:
        element = element[index]
    return element


nested_list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]

result = access_nested_element(nested_list2, indices)

print("The extracted element is:", result)

The extracted element is: 6


In [15]:
# 3. Sum of All Elements in a Nested List
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list.

    """

    total = 0

    for element in lst:
        if isinstance(element, list):
            total += sum_nested(element)
        else:
            total += element

    return total


nested_list3 = [[1, 2], [3, [4, 6]], 8]

result = sum_nested(nested_list3)

print("The sum of all elements in the nested list is:", result)

The sum of all elements in the nested list is: 24


In [16]:
# 4. Remove Specific Element from a Nested List
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    """

    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))  # recursive call
        elif item != elem:
            result.append(item)

    return result

nested_list4 = [[1, 2], [3, 2], [4, 5]]
elem = 2
output = remove_element(nested_list4, elem)

print("Modified list:", output)

Modified list: [[1], [3], [4, 5]]


In [17]:
# 5. Find the Maximum Element in a Nested List
def find_max(lst):
    """
    Finds the maximum element in a nested list.

    """

    maximum = None

    for element in lst:
        if isinstance(element, list):
            value = find_max(element)  # recursive call
        else:
            value = element

        if maximum is None or value > maximum:
            maximum = value

    return maximum

nested_list5 = [[1, 2], [3, [4, 5]], 6]

result = find_max(nested_list5)

print("Maximum element in the nested list is:", result)

Maximum element in the nested list is: 6


In [18]:
# 6. Count Occurrences of an Element in a Nested List
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    """

    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1

    return count


# Example
nested_list6 = [[1, 5], [5, 3], [2, 3]]
elem = 2

print("Occurrences:", count_occurrences(nested_list6, elem))

Occurrences: 1


In [19]:
# 7. Flatten a List of Lists of Lists
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list.

    """

    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)

    return result

nested_list7 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

print("Flattened list:", deep_flatten(nested_list7))

Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


In [21]:
# 8. Nested List Average
def average_nested(lst):
    """Calculate the average of all elements in a nested list."""
    total_sum = sum_nested(lst)
    def count_elements(l):
        count = 0
        for item in l:
            if isinstance(item, list):
                count += count_elements(item)
            else:
                count += 1
        return count
    total_count = count_elements(lst)
    return total_sum / total_count if total_count != 0 else 0

nested_list8 = [[2, 4], [6, 8], [10, 12]]
print("Average:", average_nested(nested_list8))

Average: 7.0


Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

In [22]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty Array (2x2):")
print(empty_array)

# 2. Initialize an all ones array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. Ones Array (4x2):")
print(ones_array)

# 3. Create a new array of given shape filled with a specific value
full_array = np.full((3, 3), 7)
print("\n3. Array filled with value 7:")
print(full_array)

# 4. Create a new array of zeros with the same shape and type as an existing array
zeros_like_array = np.zeros_like(ones_array)
print("\n4. Zeros array like ones_array:")
print(zeros_like_array)

# 5. Create a new array of ones with the same shape and type as an existing array
ones_like_array = np.ones_like(empty_array)
print("\n5. Ones array like empty_array:")
print(ones_like_array)

# 6. Convert a list into a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. List converted to NumPy array:")
print(numpy_array)

1. Empty Array (2x2):
[[2.03201758e-315 0.00000000e+000]
 [1.97647128e-315 1.97259029e-315]]

2. Ones Array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with value 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros array like ones_array:
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

5. Ones array like empty_array:
[[1. 1.]
 [1. 1.]]

6. List converted to NumPy array:
[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [24]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("1. Array from 10 to 49:")
print(arr1)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix from 0 to 8:")
print(arr2)

# 3. Create a 3x3 identity matrix
identity = np.eye(3)
print("\n3. 3x3 Identity Matrix:")
print(identity)

# 4. Create a random array of size 30 and find its mean
random_arr = np.random.random(30)
print("\n4. Random array of size 30:")
print(random_arr)
print("Mean of the array:", random_arr.mean())

# 5. Create a 10x10 array with random values and find min and max
rand_matrix = np.random.random((10, 10))
print("\n5. 10x10 Random Array:")
print(rand_matrix)
print("Minimum value:", rand_matrix.min())
print("Maximum value:", rand_matrix.max())

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1
print("\n6. Zero array with 5th element replaced by 1:")
print(zero_arr)

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array:")
print(reversed_arr)

# 8. Create a 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D array with border 1 and inside 0:")
print(border_array)

# 9. Create an 8x8 checkerboard matrix
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard Pattern:")
print(checkerboard)

1. Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30:
[0.36332276 0.76292223 0.9813966  0.32113206 0.42247933 0.06302327
 0.94720414 0.06865855 0.26562514 0.24068366 0.49708756 0.9620232
 0.77380232 0.73206479 0.50587323 0.76597864 0.14587644 0.97536156
 0.75399655 0.61792506 0.706943   0.27366313 0.02866917 0.00981232
 0.58935177 0.16701095 0.48987559 0.68845231 0.63160213 0.03002326]
Mean of the array: 0.49272802409843686

5. 10x10 Random Array:
[[0.37869027 0.39564791 0.8307977  0.94488121 0.46431763 0.01978577
  0.68218827 0.7969441  0.70871254 0.52083027]
 [0.07674303 0.62008386 0.50389984 0.76485221 0.52623875 0.34800166
  0.77646247 0.99842681 0.88208152 0.68847806]
 [0.26569198 0.53906784 0.21109327 0.24075193 0.7304317  0.36351618
  0.984555

Problem - 3: Array Operations:

In [26]:
import numpy as np

# Arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("1. x + y:\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\n2. x - y:\n", sub_xy)

# 3. Multiply the array with integer 3 (example)
mul_x = x * 3
print("\n3. x * 3:\n", mul_x)

# 4. Square of each element
square_x = x ** 2
print("\n4. x squared:\n", square_x)

# 5. Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\n5. Dot products:")
print("v · w =", dot_vw)
print("x · v =", dot_xv)
print("x · y =\n", dot_xy)

# 6. Concatenate arrays
concat_row = np.concatenate((x, y), axis=0)  # along rows
concat_col = np.concatenate((v.reshape(-1,1), w.reshape(-1,1)), axis=1)  # along columns
print("\n6. Concatenation:")
print("x and y along row:\n", concat_row)
print("v and w along column:\n", concat_col)

# 7. Attempt to concatenate x and v
try:
    concat_error = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("\n7. Error when concatenating x and v:")
    print(e)
    print("Explanation: x is 2x2 matrix but v is 1D array of length 2. Shapes are incompatible for concatenation along axis 0.")

1. x + y:
 [[ 6  8]
 [10 13]]

2. x - y:
 [[-4 -4]
 [-4 -3]]

3. x * 3:
 [[ 3  6]
 [ 9 15]]

4. x squared:
 [[ 1  4]
 [ 9 25]]

5. Dot products:
v · w = 219
x · v = [29 77]
x · y =
 [[19 22]
 [50 58]]

6. Concatenation:
x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w along column:
 [[ 9 11]
 [10 12]]

7. Error when concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is 2x2 matrix but v is 1D array of length 2. Shapes are incompatible for concatenation along axis 0.


Problem - 4: Matrix Operations:

In [28]:
# Matrices
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A · A^-1 = I
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("\n1. A · A^-1 = Identity matrix:\n", I)

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("BA:\n", BA)
print("AB != BA:", not np.allclose(AB, BA))

# 3. Prove (AB)^T = B^T A^T
AB_T = np.dot(A, B).T
B_T_A_T = np.dot(B.T, A.T)
print("\n3. (AB)^T = B^T A^T? ", np.allclose(AB_T, B_T_A_T))




1. A · A^-1 = Identity matrix:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB != BA: True

3. (AB)^T = B^T A^T?  True


In [29]:
# Solve system of linear equations

# Coefficient matrix
coef = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])
# Right-hand side
rhs = np.array([-1, -3, 9])

# Solve using np.linalg.solve
solution = np.linalg.solve(coef, rhs)
print("\nSolution using np.linalg.solve:", solution)

# Solve using inverse method
coef_inv = np.linalg.inv(coef)
solution_inv = np.dot(coef_inv, rhs)
print("Solution using inverse method:", solution_inv)


Solution using np.linalg.solve: [ 2.  1. -2.]
Solution using inverse method: [ 2.  1. -2.]


Experiment: How Fast is Numpy?

In [31]:
import numpy as np
import time


1. Element-wise Addition:

In [32]:
def add_lists(list1, list2):
    start = time.time()
    result = [a + b for a, b in zip(list1, list2)]
    end = time.time()
    print("Python list addition time:", end - start, "seconds")
    return result

def add_arrays(arr1, arr2):
    start = time.time()
    result = arr1 + arr2
    end = time.time()
    print("NumPy array addition time:", end - start, "seconds")
    return result


2. Element-wise Multiplication

In [33]:
def multiply_lists(list1, list2):
    start = time.time()
    result = [a * b for a, b in zip(list1, list2)]
    end = time.time()
    print("Python list multiplication time:", end - start, "seconds")
    return result

def multiply_arrays(arr1, arr2):
    start = time.time()
    result = arr1 * arr2
    end = time.time()
    print("NumPy array multiplication time:", end - start, "seconds")
    return result

3. Dot Product

In [34]:
def dot_lists(list1, list2):
    start = time.time()
    result = sum(a * b for a, b in zip(list1, list2))
    end = time.time()
    print("Python list dot product time:", end - start, "seconds")
    return result

def dot_arrays(arr1, arr2):
    start = time.time()
    result = np.dot(arr1, arr2)
    end = time.time()
    print("NumPy array dot product time:", end - start, "seconds")
    return result

4. Matrix Multiplication

In [35]:
def matmul_lists(mat1, mat2):
    size = len(mat1)
    start = time.time()
    result = [[sum(mat1[i][k] * mat2[k][j] for k in range(size))
               for j in range(size)] for i in range(size)]
    end = time.time()
    print("Python list matrix multiplication time:", end - start, "seconds")
    return result

def matmul_arrays(mat1, mat2):
    start = time.time()
    result = np.dot(mat1, mat2)
    end = time.time()
    print("NumPy array matrix multiplication time:", end - start, "seconds")
    return result

In [36]:
def run_experiment(list_size=1_000_000, matrix_size=1000):
    print("Element-wise Operations ")

    list1 = list(range(list_size))
    list2 = list(range(list_size))
    arr1 = np.arange(list_size)
    arr2 = np.arange(list_size)

    # Addition
    add_lists(list1, list2)
    add_arrays(arr1, arr2)

    # Multiplication
    multiply_lists(list1, list2)
    multiply_arrays(arr1, arr2)

    # Dot product
    dot_lists(list1, list2)
    dot_arrays(arr1, arr2)

    print("\nMatrix Multiplication")

    mat_list1 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]
    mat_list2 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]

    mat_array1 = np.arange(matrix_size * matrix_size).reshape(matrix_size, matrix_size)
    mat_array2 = np.arange(matrix_size * matrix_size).reshape(matrix_size, matrix_size)

    # Matrix multiplication
    matmul_lists(mat_list1, mat_list2)
    matmul_arrays(mat_array1, mat_array2)

run_experiment()

Element-wise Operations 
Python list addition time: 0.07178950309753418 seconds
NumPy array addition time: 0.003743410110473633 seconds
Python list multiplication time: 0.06258583068847656 seconds
NumPy array multiplication time: 0.002191305160522461 seconds
Python list dot product time: 0.08445858955383301 seconds
NumPy array dot product time: 0.0017061233520507812 seconds

Matrix Multiplication
Python list matrix multiplication time: 200.4328727722168 seconds
NumPy array matrix multiplication time: 2.170517921447754 seconds
